#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

mysql_ready() {
python << END
import sys
from sqlalchemy import create_engine
from sqlalchemy.exc import OperationalError
from config import Config

uri = Config.SQLALCHEMY_DATABASE_URI

try:
    engine = create_engine(uri)
    print (engine.table_names())

except OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until mysql_ready; do
  >&2 echo 'Waiting for database to become available...'
  sleep 1
done
>&2 echo 'Database connection suceeded!'

exec "$@"