#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

flask db upgrade
gunicorn --bind 0.0.0.0:9000 --log-level debug --workers=2 --threads=4 --worker-class=gthread --worker-tmp-dir /dev/shm wsgi:app
